### ISSUE TITLE
No WooCommerce orders are listed on MyAccount page

### ISSUE THREAD

**Issue by LucaPipolo** [flyntwp/flynt#114]
## Issue

WooCommerce orders are not listed on My Account page.
This is happening because [the `HideProtectedPosts` feature](https://github.com/flyntwp/flynt/blob/0baa2aa409c4cc5c9d23eec6f64c6c82c0e6a168/inc/hideProtectedPosts.php) is manipulating the query, adding `wp_posts.post_password = '' `.

**Comment by domtra** [comment]
Everything works fine, if you comment out this feature? 
If so, we might consider removing it from flynt by default. This feature actually implements a non-WordPress-default by not including password protected posts in archive queries. This is usually what we want but might break other use cases. 
You should be able to safely remove this file in order to get WooCommerce working properly. Hope this helps.

**Comment by LucaPipolo** [comment]
Everything seems to work fine without that feature. 

But we actually solved it adding an extra point to the condition:

```
    // We are excluding WooCommerce Account page from the query manipulation,
    // otherwise the added wp_posts.post_password = '' query condition, will
    // cause no orders to be found.
    if (!$query->is_singular() && !is_admin() && !is_account_page()) {
        $query->set('has_password', false);
    }
```

**Comment by domtra** [comment]
at the moment we are not going to change the current behaviour of flynt. it is good to know, that you have to adjust this functionality in order for woocommerce to work properly. 
closing this for now.
