### ISSUE TITLE
Gutenberg support?

### ISSUE THREAD

**Issue by kauaicreative** [flyntwp/flynt#209]
Is there documentation on accessing the Gutenberg editor?
Is there a way to restore the default wordpress editor when editing a post?

**Comment by kauaicreative** [comment]
Nice - just remove the `removeEditor.php' file

On the subject, I would be greatly interested in your future Gutenberg integration roadmap. It seems that Gutenberg will be replacing or integrating with Flynts acf components.

**Comment by domtra** [comment]
Hi @kauaicreative, thanks for reaching out.
We are really excited about Gutenberg and the way that it is evolving. However, we decided not to officially support it for now.
We want our clients to have the best editing experience in wp-admin while at the same time, making sure, that the intended design cannot be broken. We believe that these two goals are currently not achievable with ACF and Gutenberg for several reasons. But I will not go into detail here.
If you want to enable Gutenberg anyways, the way would be as you described. You might additionally need to remove or adjust the file `inc/theContentFix.php` because there we add a shortcode to render a post's 
components to `post_content`. 
Are you then still using the Flynt components as regular meta fields in Gutenberg? While this would work, I doubt that this will lead to a desirable state. One main functionality of Flynt is the use of components in a flexible content field. Gutenberg basically offers an alternative to flexible content. Using both on a post type would not make sense in most cases.
There is a way to make Flynt components available in in Gutenberg natively via ACF. You can get some inspiration from https://github.com/flyntwp/flynt/pull/19. 
We have no fixed roadmap on when to include this functionality with Flynt. Currently, we are concentrating on fine tuning existing features, not adding new ones. But after that, Gutenberg support will probably be a feature we will add.
I would be really interested to see what you end up with, so feel free to keep us posted about any updates.
Is there anything else you would like to know about Flynt?

**Comment by kauaicreative** [comment]
Thanks for the detailed explanation! 
I totally understand. Flynt's current component system would be simpler for a typical client to grasp. 
I'll keep you posted.

**Comment by trompx** [comment]
Hello @domtra ,

I am about to create a starter theme for multiple websites so I would like to have a solid base. I have the same goals of providing my clients with a clean editing experience in wp-admin and making sure they don't break the design, thus designing myself some blocks/components and allow them to only fill the required data.

I've been searching among a lot of wordpress projects (old and recent) and it seems gutenberg is in the right direction. I had a first page builder draft (before finding flynt) using ACF flexible content but I found the editing experience not so great (lacking vizualisation).
I researched gutenberg a lot and am now hesitating to use it with ACF blocks (blocks can have image previews just like in flynt), while disabling all the base blocks coming with gutenberg to not confuse my clients.

But now that I stumble upon your project, I am doubting. I love the fact that gutenberg is in the core and that the interface look modern.
Would you mind expanding on the several reasons why you chose to create your own page builder (which kind of remind me of the flothemes themes backend) and why you think the goals are currently not achievable with ACF blocks + Gutenberg?

**Comment by zschuessler** [comment]
+1 for revisiting a Gutenberg discussion. Working with many agencies since Gutenberg was released, I've seen:

1. The initial "we hate it" sentiment from clients go to "we need all our sites with Gutenberg" within a year. No one wants to use the old page builders, either. (Anecdotal, YMMV)
2. Popular builders like Beaver Builder, WP Bakery, etc found new ways to pivot outside their old business models - knowing from market data that Gutenberg was replacing them
3. WordPress officially dropping support for the old editor

Sorry to revive a conversation that it looks like Flynt team doesn't want to have. And I'll say first: _amazing_ work building Flynt_. But I can't use Flynt on projects and I would really like to - it's beautiful. I don't feel confident I could get clients onboard to use it, but I'm happy if it works for your team. I do wonder if this is sunk cost fallacy?

I would even be open to use a fork of Flynt that caters to Gutenberg even if that meant less support. Work has already been done here:
https://github.com/flyntwp/flynt/issues/17

**Comment by steffenbew** [comment]
Thanks for bringing up the topic again, @zschuessler. 

Each time we're discussing Gutenberg support at bleech, we agree that simple solutions would vastly benefit from it, but we remain concerned about more complex solutions. And when thinking about a specific Flynt/Gutenberg solution, I'm questioning if ACF is the best option, or if a pure Gutenberg solution should be the way.

I've got 2 questions that would help me keep the conversation going:
1. What's your opinion about and experience with more complex sites using Gutenberg? Are we too cautious?
2. Why would Flynt be a good choice over ___________ (insert any other Gutenberg Starter Theme)?

**Comment by zschuessler** [comment]
Amazing questions, thanks for taking the time to respond.

> thinking about a specific Flynt/Gutenberg solution, I'm questioning if ACF is the best option, or if a pure Gutenberg solution should be the way.

I've tried several options, including doing straight Gutenberg (both via React and using server-side rendering). Going straight Gutenberg was a complete nightmare because the WordPress docs weren't helpful on documenting features (and especially the many edge cases we hit). Gave it an honest go for a week and gave up, we were spending too much time on the wrong problems. Server-side rendering (which ACF supports!) was better, but at that point it just makes sense to use ACF's tools for various time-saving reasons.

The biggest benefit to ACF is that clients love it, it's easy to understand, setup, and configure. The forms/preview work _really_ well. If you try to implement the same thing ACF did in straight Gutenberg, if you're like me you'll quickly grow fond appreciate of ACF. It's just too time consuming to create a good user experience without problems.

The biggest argument for straight Gutenberg IMO, is more flexibility in highly custom editing (like in-place editing) but to be honest, I think that's confusing for non-techie users while, ACF forms are intuitive.

> What's your opinion about and experience with more complex sites using Gutenberg? Are we too cautious?

I've used ACF-based Gutenberg blocks on maybe 20-30 unique builds over the years, both large and small. I've never had an issue even in the early days when ACF released it, whether it was performance (large forms lagging the admin page) or upgrades. You'll find in implementing straight Gutenberg you'd need to account for block schemas/behavior changing from one version of your block implementation to the next, and ACF executes this complex behavior flawlessly.

ACF stores the metadata for blocks (and values) in the post as json, it's very easy to both query the data and write custom mutators/accessors as a result.

The server-side rendering of blocks ACF offers fits very well with the idea of an all-contained component. Your render function can call whatever templating language it wants, there are hooks to tap into for styles/javascript, etc. In fact, we use the same component idea that Flynt uses but with ACF for blocks (twig template, css, js, etc all in one folder).

Last but not least, the ACF team have been very good about pushing new features and maintaining the blocks feature. They have iterated on releases quickly.

> Why would Flynt be a good choice over ___________ (insert any other Gutenberg Starter Theme)?

Flynt hit all these major requirements that others don't (I've reviewed every free/paid option I can find). And the only reason we haven't already bought the $499 license is because of native Gutenberg support. Here is what stands out about Flynt I don't see others execute as well in the same space:

1. Amazingly well done documentation, truly good stuff here!
2. Great well-though out features that adhere to your own internal consistent code standards, and not too opinionated on development implementation
3. Actively developed, actively adopted, and excellent release system
4. Accompanying toolkit/repos and adoption. And in general, the Flynt team seems like they thought everything out for a good developer experience.
5. Long list of well done components that would save agencies time in iterating on a design. If  I can hand off a full list of components our designers could use as wireframes ([and I can](https://flyntwp.com/components/)) that gives us a massive efficiency boost. Love it. If you had a community/marketplace for blocks too, that'd be a massive value add.

I really can't say anything else other than Gutenberg support would hold us back. The only nit I have is not using PSR standards, but that is purely opinionated and in no way would prevent us from using Flynt.

Thanks again for taking the time to respond! If you have further questions lmk

**Comment by steffenbew** [comment]
Thanks a ton for your elaborate response, @zschuessler! I very much appreciate your insights and opinion.
I just put Gutenberg on the agenda for the next Flynt Jour Fixe. We will thoughtfully consider your input.
Expect an update here, but please give us some time.

**Comment by eduwass** [comment]
@steffenbew I was wondering what is the final status on this, does Flynt not support blocks at the moment?

Thanks!

**Comment by steffenbew** [comment]
@eduwass The Flynt theme is Gutenberg-ready since v2.0 with the block editor being activated by default for posts. It continues to use ACF Flexible Content to manage components on pages. With great advancements being made in the Gutenberg project this year, I'm looking forward to what's coming to Gutenberg in 2024.
