### ISSUE TITLE
Move component to another page

### ISSUE THREAD

**Issue by aalyokhin** [flyntwp/flynt#218]
Hi guys. Many thanks for all your work.

Could you please clarify if there is a possibility to move a component to another page? It seems like a very basic functionality, however I wasn't able to do this, no matter how long I was trying to. Let's assume I have some component with lots of data set up for a homepage, and I want to move it to some other page with all its data, is it correct that I will need to enter all content once again? That may be unbelievable waste of time. 

I was trying a few plugins, like [ACF Extended](https://wordpress.org/plugins/acf-extended/), but it didn't help with the problem, the only thing I noticed is possibility to clone component within same page, but not to another one.

Thanks a lot in advance for your help!

Alex

**Comment by steffenbew** [comment]
Hi Alex,

the fields functionality is dependent on ACF Pro. I don't have any experience with moving field data to another page, besides what you mentioned: copying full pages and modifying from there.
However, I just found a plugin that aims to provide a similar functionality: https://wordpress.org/plugins/acf-flexible-layouts-manager/

But why did we not come across this issue before? Mostly because we would set up reusable content as custom post types or as global or translatable options. But still, I feel being able to move and copy components would be a nice feature, so please keep us posted if you find a plugin that does that really well.

Best,
Steffen

**Comment by cbirdsong** [comment]
This feature would essentially come for free with Flynt components implemented as ACF blocks in Gutenberg (see #17/#19). You can mark a block as "reusable" and then have a repeated always-updated instance of it across a site.
