### ISSUE TITLE
Logotype (Feature request)

### ISSUE THREAD

**Issue by patrickdanielsson** [flyntwp/flynt#232]
Love this framework, it would be great it had support for `custom_logo` aswell.

**Comment by pixelsaft** [comment]
We added a Global Option field and changed the code into the two navigation components to make this possible.

**Comment by patrickdanielsson** [comment]
The reason why I want to use `custom_logo` is that is also used by other plugins. And this is the field that should be used for the logotype.

**Comment by pixelsaft** [comment]
To enable the support inside the theme add `add_theme_support( 'custom-logo' );` to the file **theme.php** inside the **inc** folder.

`add_action('after_setup_theme', function () {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    **add_theme_support( 'custom-logo' );**
});`

After that you must catch the custom-logo inside add_filter from the two navigation components and in the last step the twig files from these components should be changed.

**Comment by steffenbew** [comment]
I like the idea of using `custom-logo` as it's a standard WordPress approach. The reason we don't use it right now is because it would be the only thing that's found in the customizer. Every other option is in an ACF options page (General Options or Translatable Options). So it might be confusing and inconsistent to use both. But will still give it another thought and update you here.

**Comment by steffenbew** [comment]
@patrickdanielsson @pixelsaft We just added the customer support for the logo in this pull request: https://github.com/flyntwp/flynt/pull/257
