### ISSUE TITLE
Helpers::extractNestedDataFromArray is missing

### ISSUE THREAD

**Issue by szepeviktor** [flyntwp/flynt#245]
Was in https://github.com/flyntwp/flynt-core/blob/fa3bfff0559a8e07c9fa37817b073f4c6cca3864/lib/Flynt/Helpers.php#L7-L14

**BUT** referenced in [lib/Defaults.php:45](https://github.com/flyntwp/flynt/blob/0338027dca6ed54dd96128c8e720ab6299ef30dd/lib/Defaults.php#L45)

**Comment by domtra** [comment]
hi @szepeviktor 

thanks for the info. Great find! 

The `renderComponent` function is kind of a relic and not used by us anymore. Currently we only use the twig function. We will either remove the render part from defaults, or fix it so that the twig function uses the same logic.

Did you run into any issues with that and what was the use case? Or did it come out of a static analysis.

Cheers.

**Comment by szepeviktor** [comment]
> Did you run into any issues with that and what was the use case? Or did it come out of a static analysis.

I am not a Flynt user, nor a developer.

I just run PHPStan on projects expected to be use by my clients - like a food taster.

**Comment by szepeviktor** [comment]
Please get rid of relics!
