### ISSUE TITLE
How can I add my new class for new wordpress custom widget?

### ISSUE THREAD

**Issue by forevereffort** [flyntwp/flynt#251]
I made the file like the following:

`themes\flynt\Components\SiteFooter\Widgets\WPMobileAppNavMenuWidget.php`

and that file content like the following:

```
<?php

namespace Flynt\Components\SiteFooter\Widgets;

use WP_Widget;

class WPMobileAppNavMenuWidget extends WP_Widget
{
....
}
```

and I tried to use above Class in `themes\flynt\Components\SiteFooter\functions.php`

like this

```
<?php

namespace Flynt\Components\SiteFooter;

use Flynt\Components\SiteFooter\Widgets\WPMobileAppNavMenuWidget;

add_action('widgets_init', function () {
    register_widget('Flynt\Components\SiteFooter\Widgets\WPMobileAppNavMenuWidget');
})
```

but it didn't worked. so I added the require function like the following

```
<?php

namespace Flynt\Components\SiteFooter;

require_once dirname(__FILE__) . '/Widgets/WPMobileAppNavMenuWidget.php';

add_action('widgets_init', function () {
    register_widget('Flynt\Components\SiteFooter\Widgets\WPMobileAppNavMenuWidget');
})

```

after that, code is working.
but I would like to avoide to use require_once.
how can I do this on Flynnt theme?
thanks

**Comment by domtra** [comment]
Hi @forevereffort ,
for components we only load the `functions.php`. The rest you need to do manually. So that you need a `require_once` is actually expected behaviour. 
The alternative would be to put the Widget code into the `./lib` folder. In there everything is psr-4 autoloaded and you would not need to require the file manually.
I hope this answers your question.

**Comment by forevereffort** [comment]
@domtra, thank you very much
