### ISSUE TITLE
editor-style  technique

### ISSUE THREAD

**Issue by proteinone** [flyntwp/flynt#285]
Hello team Flynt (and Bleech)!

I normally create an editor-style.css so I can customise the css within the TinyMce editor.  And since the theme is using SASS, it makes sense to try and utilise the SASS process to generate this stylesheet, so it can inherit styles.

This is how I achieved it - is this a good method, or would you guys have achieved this in a more optimal way?
In an ideal world I wouldn't want to be editing the build-config.js, but I didn't see any other way?

/build-config.js
```
  webpack: {
    entry: {
      "assets/main": "./assets/main.js",
      "assets/admin": "./assets/admin.js",
      "assets/editor-style": "./assets/editor-style.js",
    },
    copy: [getCopyConfig("./Components/**/*"), getCopyConfig("./assets/**/*")],
  },
```

/inc/tinyMce.php
```
// Editor Styles
add_editor_style('dist/assets/editor-style.css');
```

/assets/editor-style.js
```
import "./scripts/publicPath";
import "./editor-style.scss";

function importAll(r) {
  r.keys().forEach(r);
}

importAll(require.context("../Components/", true, /\/editor-style\.js$/));
```

/assets/editor-style.scss
```
@import "styles/variables";
@import "styles/mixins";
@import "styles/base";
etc.
```

Cheers,
Tim

p.s. I'm loving the new theme release v1+.  So thank you for that!
It's a huge improvement over the beta version, and already feels a lot faster to use : )

**Comment by koukouchris** [comment]
Hello @proteinone,

This is very similar to our approach, when adding editor styles. 
We also add a new entry in the build-config.js because this will create a new, separate bundle.

/assets/editor-style.js would look like this:
`import './editor-style.scss'`

We usually only add global styles and not component specific ones. So that is why you do not necessarily need the import stuff in the editor-style.js.

We add editor styles on /inc/assets.php
```
add_action('admin_init', function () {
    add_editor_style(Asset::requireUrl('assets/editor-style.css'));
});
```

We handle all asset loading in inc/assets.php and do not create an extra tinyMce.php, but this is just preference.

The `Asset::requireUrl` is a helper to resolve the correct path of a given assets. 
This most of the time just makes a difference when you run `npm run build`, then all assets are revisioned, so they get a content hash added to their filename.


Thanks for the feedback! Glad you're enjoying Flynt!

**Comment by proteinone** [comment]
Thanks @koukouchris !

Great to hear we were on the right path : )

I completely agree about the editor-style.js, we don't need component level styles either.

And the assets.php looks like a better place to enqueue the file also. Good idea.
