### ISSUE TITLE
Date in posts

### ISSUE THREAD

**Issue by robertmain53** [flyntwp/flynt#345]
Hi, 
I've tried Flynt v1.4.0 both locally and on (Apache).
In both cases I have found that the BlockPostHeader shows today's date, not the date on which the post was written or the date on which the post was modified.

**Comment by Loualex** [comment]
I guess you have to use also post.post_date|date instead of post.date.

`<time class="meta-date" datetime="{{ post.post_date }}">{{ post.date|date }}</time> {{ dividers.authorDivider|e }}`
In datetime its correct.

**Comment by Auroraboreali-s** [comment]
I've experienced the same issue FlyntWP v1.4.0. 

In the Components/BlockPostHeader/index.twig

`<time class="meta-date" datetime="{{ post.post_date }}">{{ post.date|date }}</time> {{ dividers.authorDivider|e }}`

replaced to

`<time class="meta-date" datetime="{{ post.post_date }}">{{ post.date }}</time> {{ dividers.authorDivider|e }}`

does the trick and retrieves the publication date instead of the current date, so removing the |date

**Comment by aaronmeder** [comment]
🌐 We have a Translatable Setting to specify a language specific date format (e.g. "**dateFormat**" in the example) and then use this for processing the date:

`{{ post.date|date(**dateFormat**) }}`

**Comment by domtra** [comment]
@robertmain53 , @Loualex , @Auroraboreali-s , @aaronmeder , Thanks for all of your input.

This issue is a strange one. As for our normal setup, the code works fine, as is. flyntwp.com always reflects our master branch. And if you check [here](https://flyntwp.com/the-beginners-guide-to-developing-a-custom-wordpress-theme-with-flynt/) it does actually display the correct date.

However, we also have run into issues with this not showing the correct date. 

I have opened a pull request with a fix that also includes using the general wordpress option for the date format and included the time zone for the datetime stamp. This should all lead to the issue not being present anymore.
