### ISSUE TITLE
Gravity Forms Support

### ISSUE THREAD

**Issue by ryanatduckpin** [flyntwp/flynt#359]
I have been having issues implementing Gravity Forms with conditional fields / datepicker fields. I believe it has to do with the core jquery related scripts loading. I have been trying to adjust the order for the form to work correctly with no luck.

**Comment by filipe-q** [comment]
Are you loading jquery in the head or the end of the body?

**Comment by ryanatduckpin** [comment]
End of the body. I tried to get it to load in the header and I wasn't able to. Flynt modifies the jquery script by dregestering it and loading the same version from ajax.googleapis.com. I disabled that, and it still loaded in the footer. I then tried using the `Asset::register()` function, which takes a parameter to load it in the footer/header, and it still didn't work. Can I get another pair of eyes on this?

**Comment by filipe-q** [comment]
Try this in `/flynt/inc/Assets.php`
```
add_action('wp_enqueue_scripts', function () {
    Asset::enqueue([
        'name' => 'Flynt/assets',
        'path' => 'assets/main.js',
        'type' => 'script',
        'inFooter' => true,
        'dependencies' => ['jquery'],
]);
```
What this means is that the main.js will load in the footer and after jquery is loaded.

Also, the following code by itself will not load jquery from the CDN:
```
add_action(
    'wp_enqueue_scripts',
    function () {
        $jqueryVersion = wp_scripts()->registered['jquery']->ver;

        wp_deregister_script('jquery');

        $jqueryLocalUrl = esc_url(includes_url("/js/jquery/jquery.js?ver=${jqueryVersion}"));
        Asset::register([
            'name' => 'jquery',
            'cdn' => [
                'url' => "//ajax.googleapis.com/ajax/libs/jquery/${jqueryVersion}/jquery.min.js",
                'check' => 'window.jQuery',
            ],
            'type' => 'script',
            'path' => $jqueryLocalUrl,
            'inFooter' => true,
        ]);
    },
    0
); // NOTE: prio needs to be < 1
```

Flynt will only load assets through the CDN if you set the CDN variable to true here: [https://github.com/flyntwp/flynt/blob/371abbb9bf3d118ae8377d5d1ddc2084bae041d4/lib/Init.php#L19](url)

**Comment by MyEmpireOfDuctTape** [comment]
Hi! I have also had a similar issue on a previous project. The main cause of the problem was that jQuery was being loaded twice. This means that initially it was loaded with 1.4 (I believe) and then later on a different version would load. This mean sthat all the listeners that had been set by gravity forms with the previous jQuery never triggered. This can be fixed by making sure that it is not loaded twice. You can illustrate and debug this by sticking `console.log(jQuery.fn.jquery)` in both the plugin code when the listeners are set, and then once again at the end of the footer.

**Comment by domtra** [comment]
To give a little more context:
I most versions of flynt, we bundle a separate version of jQuery in our main javascript bundle. This was done for multiple reasons. For example because WordPress used jQuery v1.x instead of 3.x. With this in mind, when using a WordPress plugin for the frontend, that depended on jQuery, you needed to adjust the script registration for these plugins a bit. But mostly, this led to issues.
Since WordPress finally upgraded its jQuery version to 3.x, we are making changes for the next flynt version to use this instead of separate one in our js bundle.

In order to resolve your issues with Gravity Forms, you could to the same. See this commit: https://github.com/flyntwp/flynt/commit/75c0bba7f674a1fb70d7253db76aeac864425844

In addition to multiple jQuery versions being loaded, another issue is, that we deferred the loading of the javascript. This is a know issues with Gravity Forms, see https://community.gravityforms.com/t/deferring-javascript-without-breaking-gravity-forms/5731

So if you use the default WordPress jQuery version but still experience issues, it is probably related to an additional caching or speed optimisation plugin, that modifies the loading behaviour of your scripts.

Let me know if this helps.

**Comment by ryanatduckpin** [comment]
The commit 75c0bba fixed the issue for me! Thanks @domtra

**Comment by psquirrel2018** [comment]
@domtra, I followed your advice here in The commit https://github.com/flyntwp/flynt/commit/75c0bba7f674a1fb70d7253db76aeac864425844 and I am still getting js errors when using gravity forms.  Is there a new fix or something else I should try?

**Comment by psquirrel2018** [comment]
@domtra You can ignore my comment.  I am not sure what my issue was, but when I rebuilt my site with a fresh install of flyntwp v1.4.0 the js errors went away and gravity forms is working now.
