### ISSUE TITLE
Issue with GitHub

### ISSUE THREAD

**Issue by camscottFS** [flyntwp/flynt#379]
Hey, for some reason the entire folder won't commit. This didn't happen with Flynt 1.3

Any idea?

![image](https://user-images.githubusercontent.com/7515080/117207910-21f29380-adba-11eb-9f24-91d6f7a9b474.png)

**Comment by domtra** [comment]
Hi @camscottFS, 
I am sorry, but I do not understand what exactly the issue is?
Flynt is only the theme, so i am guessing that you called it `mmember-v2` in your project. Is this correct?
You also made some changes to the `.gitignore` file, maybe these are preventing you from adding files to the repo?
Is `mmember-v2` actually a directory that you can open and browser files in, or did for some reason the archive not get extracted or something similar?

**Comment by camscottFS** [comment]
Problem was .git folder.
