### ISSUE TITLE
How can we call the shortcodes in flynt ?

### ISSUE THREAD

**Issue by rajpatel2435** [flyntwp/flynt#542]
### Discussed in https://github.com/flyntwp/flynt/discussions/541

<div type='discussions-op-text'>

<sup>Originally posted by **rajpatel2435** March 26, 2024</sup>
Hey guys, is there anyone who has the complete documentation for flynt? As I started working on this theme for my new project. But I am not sure how can i start? Any advice would be highly appreciated!!

Thanks</div>

**Comment by timohubois** [comment]
@rajpatel2435 thanks for opening the issue. 

To render shortcodes you can take a look at the Twig Filters of the timber documentation here:
https://timber.github.io/docs/v2/guides/twig-filters/#shortcodes

And for layouts with shortcodes you find also details here:
https://timber.github.io/docs/v2/guides/shortcodes/#layouts-with-shortcodes

In general I think the subject and the topic is not an issue of the theme itself, because shortcodes should work as aspected or did you run in any trouble while processing shortcodes?
